#ifndef USBD_REQUEST_H
#define USBD_REQUEST_H

#include "stm32l4xx.h"

#define USBD_REQUEST_DIRECTION (0x1UL << 7)
#define USBD_REQUEST_DIRECTION_IN (0x1UL << 7)
#define USBD_REQUEST_DIRECTION_OUT (0x0UL << 7)

#define USBD_REQUEST_TYPE (0x3UL << 5)
#define USBD_REQUEST_TYPE_STANDARD (0x0UL << 5)
#define USBD_REQUEST_TYPE_CLASS (0x1UL << 5)
#define USBD_REQUEST_TYPE_VENDOR (0x2UL << 5)
#define USBD_REQUEST_TYPE_RESERVED (0x3UL << 5)

#define USBD_REQUEST_RECIPIENT (0xFUL << 0)
#define USBD_REQUEST_RECIPIENT_DEVICE (0x0UL << 0)
#define USBD_REQUEST_RECIPIENT_INTERFACE (0x1UL << 0)
#define USBD_REQUEST_RECIPIENT_ENDPOINT (0x2UL << 0)
#define USBD_REQUEST_RECIPIENT_OTHER (0x3UL << 0)

#define USBD_REQUEST_GET_STATUS 0
#define USBD_REQUEST_CLEAR_FEATURE 1
#define USBD_REQUEST_SET_FEATURE 3
#define USBD_REQUEST_SET_ADDRESS 5
#define USBD_REQUEST_GET_DESCRIPTOR 6
#define USBD_REQUEST_SET_DESCRIPTOR 7
#define USBD_REQUEST_GET_CONFIGURATION 8
#define USBD_REQUEST_SET_CONFIGURATION 9
#define USBD_REQUEST_GET_INTERFACE 10
#define USBD_REQUEST_SET_INTERFACE 11
#define USBD_REQUEST_SYNCH_FRAME 12

#define USBD_REQUEST_DESC_DEVICE 1
#define USBD_REQUEST_DESC_CONFIGURATION 2
#define USBD_REQUEST_DESC_STRING 3
#define USBD_REQUEST_DESC_INTERFACE 4
#define USBD_REQUEST_DESC_ENDPOINT 5
#define USBD_REQUEST_DESC_DEVICE_QUALIFIER 6
#define USBD_REQUEST_DESC_OTHER_SPEED_CONFIGURATION 7
#define USBD_REQUEST_DESC_INTERFACE_POWER 8
#define USBD_REQUEST_DESC_BOS 15
#define USBD_REQUEST_DESC_DEVICE_CAPABILITIES 16

typedef struct
{
	uint8_t bmRequestType;
	uint8_t bRequest;
	uint16_t wValue;
	uint16_t wIndex;
	uint16_t wLength;
}__PACKED usbd_setup_packet_type;

#endif /*USBD_REQUEST_H*/